name: Publish package to npm

on:
  release:
      types: [created]

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true # Only run on merged pull requests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
